### ISSUE TITLE
Typo: Misspelling on welcome page

### ISSUE THREAD

**Issue by tanryberdi** [ayeressian/dbgrapher#60]
We need to fix Wellcome --> Welcome
<img width="740" alt="Screenshot 2023-02-06 at 09 10 43" src="https://user-images.githubusercontent.com/2136923/216881987-b0c2d074-b5c2-4787-bf66-968b5a0568de.png">

**Comment by ayeressian** [comment]
@tanryberdi thank you for letting me know. The fix will be merged soon.

**Comment by ayeressian** [comment]
merged

**Comment by tanryberdi** [comment]
> @tanryberdi thank you for letting me know. The fix will be merged soon.

you are welcome, man?
